### ISSUE TITLE
"If so" should accept any statement, not only "Let us..."

### ISSUE THREAD

**Issue by GallowsDove** [zmbc/shakespearelang#10]
If there is for example a statement:
 If so, you are as cowardly as a chihuahua.

this should be also considered as valid input, however, currently it throws parser error:
"expecting one of: Let We"

**Comment by zmbc** [comment]
Thank you for reporting this @GallowsDove!

I only noticed a few months ago that the spec said conditionals (both "If so" and "If not") can apply to any sentence type. I am currently doing a major overhaul of this package and this is one of the issues I hope to correct in the next release.

**Comment by zmbc** [comment]
A bit late here (it's been out since January) but `1.0.0rc1` supports this -- feel free to test it out!
