### ISSUE TITLE
No module named 'readline'

### ISSUE THREAD

**Issue by stuart-thomas-zoopla** [zmbc/shakespearelang#20]
Installed shakrespearelang and ran the example .spl and got the following error

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\new\AppData\Local\Programs\Python\Python312\Scripts\shakespeare.exe\__main__.py", line 4, in <module>
  File "C:\Users\new\AppData\Local\Programs\Python\Python312\Lib\site-packages\shakespearelang\cli.py", line 7, in <module>
    from ._repl import start_console, debug_play
  File "C:\Users\new\AppData\Local\Programs\Python\Python312\Lib\site-packages\shakespearelang\_repl.py", line 6, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'`

it seems that there is an import of an unused and missing module here

https://github.com/zmbc/shakespearelang/blob/a4a2753ff7bccd9cde4d525f9282f00930232076/shakespearelang/_repl.py#L6

removing that import fixes it and the output is as expected

**Comment by zmbc** [comment]
Hi @stuart-thomas-zoopla! Thanks for using `shakespearelang`!

It's actually not an unused import -- simply _importing_ readline changes the behavior of `input()`. However, I did not realize when I wrote this that readline is only available on Unix-like systems. It doesn't work on Windows.

I'd be happy to accept a PR that wraps the import in a `try` block!

**Comment by stuart-thomas-zoopla** [comment]
Ah ok, that makes sense.  PR Incoming.

**Comment by zmbc** [comment]
Immediate issue fixed by #21, though broader support for Windows is a bit unclear.

**Comment by JanEricNitschke** [comment]
Hi, i think this newest version has not been pushed onto PyPI and thus the install from there still errors on windows. Would be awesome if you could update the version there.
